### ISSUE TITLE
Overlay 不能全屏

### ISSUE THREAD

**Issue by charlzyx** [rnxteam/rnx-ui#14]
开发过程遇过一种情况,  需要ActionSheet 的组件在比较深的子组件中, 而该子组件的父组件是 absolute 定位的, 因此导致 Overlay 不能全屏.

示意图:

![image](https://user-images.githubusercontent.com/18055018/28824290-fbe17e6e-76f3-11e7-8113-26ff6dc78585.png)

- 建议解决方案: 使用[React Native / Modal](http://facebook.github.io/react-native/releases/0.33/docs/modal.html#modal)

**Comment by dragonwong** [comment]
Modal 会覆盖在 RN 的所有页面上，隐藏 Modal 的显隐和页面状态的关系往往不太好处理。建议是把 ActionSheet 放在较浅节点（根节点）范围使用。

**Comment by dragonwong** [comment]
感谢反馈，issue 先关了哈，还有问题欢迎讨论！
