### ISSUE TITLE
RefreshView无上拉加载和下拉刷新状态标题配置

### ISSUE THREAD

**Issue by FDKPIBC** [rnxteam/rnx-ui#24]
rt,代码中也并无与此相关内容,展示效果的gif倒是有相关内容的展示

**Comment by dragonwong** [comment]
@FDKPIBC https://github.com/rnxteam/rnx-ui/blob/39427e2385841bc2a996fea3339b6bd132e3142b/Example/src/page/RefreshView/index.js 这里有的
