### ISSUE TITLE
一点微小的建议

### ISSUE THREAD

**Issue by iamcco** [rnxteam/rnx-ui#3]
像 ToolTip 这个组件的这种 pointerEvents 属性参数，坠吼可以在 readme 里面枚举粗来，一点微小的建议，谢谢

**Comment by malcolmyu** [comment]
@iamcco 滋瓷，可心妹子正在做 web 版的文档，到时候加上

**Comment by dragonwong** [comment]
@iamcco 很馋愧，下一版加上

**Comment by dragonwong** [comment]
fixed #5
